export const ActionTypes = {
  FETCH_ASSISTANTS: 'FETCH_ASSISTANTS',
  SET_ASSISTANTS: 'SET_ASSISTANTS',
  SELECTED_ASSISTANT: 'SELECTED_ASSISTANT',
  REMOVE_SELECTED_ASSISTANT: 'REMOVE_SELECTED_ASSISTANT'
}

// export const SET_ASSISTANTS = 'SET_ASSISTANTS'
